#- RandomSamplingDataPointsFilter:
# reduces the size of the point cloud by randomly dropping points.
    #prob: 0.15 # probability to keep a point, one over decimation factor.

- OctreeGridDataPointsFilter:
    maxPointByNode: 80 # number of point under which the octree stop dividing. neg: 80-~4200
    maxSizeByNode: 0.5 #size of the bounding box under which the octree stop dividing.
    samplingMethod: 3 # method to sample the octree: Medoid.

- SurfaceNormalDataPointsFilter:
# extracts the normal to each point by taking the eigenvector corresponding to the smallest eigenvalue of its nearest neighbors.
#- SamplingSurfaceNormalDataPointsFilter:
# decomposes the point-cloud space in boxes, by recursively splitting the cloud through axis-aligned hyperplanes.
# When the number of points in a box reaches a value knn or lower, the filter computes the center of mass of these
# points and its normal by taking the eigenvector corresponding to the smallest eigenvalue of all points in the box.
    #ratio: 0.03
    knn: 10
    keepNormals: 1
